---
service_id_1: 1d7905ad-b3f7-49fb-b8a2-e0b697be8da7
docker_compose_file_1: "{{ lookup('file', './files/docker-compose.yml') | from_yaml }}"

service_id_2: 8a5fe964-8031-4439-b4b2-3dbde357b73a
docker_compose_file_2: "{{ lookup('file', './files/docker-compose-with-host-network.yml') | from_yaml }}"

service_id_win: 1d7905ad-b3f7-49fb-b8a2-e0b697be8da7
docker_compose_file: "{{ lookup('file', './files/docker-compose.yml') | from_yaml }}"
docker_compose_file_win: "{{ lookup('file', './files/docker-compose-win.yml') | from_yaml }}"