---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: ubuntu1804
    image_name: Ubuntu 18.04 64-bit
    groups: ['ssh']
provisioner:
  name: ansible
  inventory:
    host_vars:
      ubuntu1804: 
        ansible_python_interpreter:  "/usr/local/bin/python3.12"
  playbooks:
    create: ../default/create-os.yml
    destroy: ../default/destroy-os.yml
    prepare: ../default-deploy/prepare.yml
    converge: ../default-deploy/converge.yml
    verify: ../default-deploy/verify.yml
verifier:
  name: ansible
