---
- name: Install required roles
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Install required roles
      ansible.builtin.command:
        cmd: ansible-galaxy role install -f -r ../../../requirements.yml

    - name: Ensure Molecule roles directory exists
      ansible.builtin.file:
        path: "{{ playbook_dir }}/roles"
        state: directory
        mode: "0755"

    - name: Link "use" role for Molecule
      ansible.builtin.file:
        src: "{{ playbook_dir }}/../../../use"
        dest: "{{ playbook_dir }}/roles/use"
        state: link
        force: true

- name: Ensure compatible python version
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Install Python
      ansible.builtin.include_role:
        name: slm-ansible-role-python

- name: Install docker
  hosts: all
  gather_facts: true
  become: true
  vars:
    state: present
  tasks:
    - name: Install docker
      ansible.builtin.include_role:
        name: "docker"
