---
- name: Set service_id and docker_compose_file - service-1
  ansible.builtin.set_fact:
    docker_compose_file: "{{ docker_compose_file_1 }}"
    service_id: "{{ service_id_1 }}"

- name: Include verify helper - service-1
  ansible.builtin.include_tasks: verify-linux-helper.yml

- name: Set service_id and docker_compose_file - service-2
  ansible.builtin.set_fact:
    docker_compose_file: "{{ docker_compose_file_2 }}"
    service_id: "{{ service_id_2 }}"

- name: Include verify helper - service-2
  ansible.builtin.include_tasks: verify-linux-helper.yml