---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: centos7
    image_name: ansible-dev-centos-7

  - name: centos8
    image_name: ansible-dev-centos-8-stream

  - name: centos9
    image_name: ansible-dev-centos-9-stream
provisioner:
  name: ansible
  playbooks:
    create: ../default/create-os.yml
    destroy: ../default/destroy-os.yml
    prepare: ../default-deploy/prepare.yml
    converge: ../default-deploy/converge.yml
    verify: ../default-deploy/verify.yml
verifier:
  name: ansible
