---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: debian11
    image_name: Debian 11 64-bit (Ansible)
    groups: ['ssh']
provisioner:
  name: ansible
  playbooks:
    create: ../default/create-os.yml
    destroy: ../default/destroy-os.yml
    prepare: ../default-deploy/prepare.yml
    converge: ../default-deploy/converge.yml
    verify: ../default-deploy/verify.yml
verifier:
  name: ansible
