---
- name: Prepare
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: "Include setup - install"
      when: ansible_os_family != "Windows"
      ansible.builtin.include_role:
        name: "setup"
        tasks_from: install.yml

    - name: Include vars file
      include_vars:
        file: ./vars/main.yml

    - name: LINUX Deployment
      when: ansible_os_family != "Windows"
      block:
        - name: "Include use - deploy (service-1)"
          include_role:
            name: "use"
            tasks_from: deploy.yml
          vars:
            service_id: "{{ service_id_1 }}"
            docker_compose_file: "{{ docker_compose_file_1 }}"

        - name: "Include use - deploy (service-2)"
          include_role:
            name: "use"
            tasks_from: deploy.yml
          vars:
            service_id: "{{ service_id_2 }}"
            docker_compose_file: "{{ docker_compose_file_2 }}"

    - name: WINDOWS Deployment
      when: ansible_os_family == "Windows"
      block:
        - name: "Include use - deploy (service-1)"
          include_role:
            name: "use"
            tasks_from: deploy.yml
          vars:
            service_id: "{{ service_id_1 }}"
            docker_compose_file: "{{ docker_compose_file_1_win }}"

        - name: "Include use - deploy (service-2)"
          include_role:
            name: "use"
            tasks_from: deploy.yml
          vars:
            service_id: "{{ service_id_2 }}"
            docker_compose_file: "{{ docker_compose_file_2_win }}"