---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: ubuntu2204
    image_name: Ubuntu 22.04 64-bit
    groups: ['ssh']
provisioner:
  name: ansible
  playbooks:
    create: ../default/create-os.yml
    destroy: ../default/destroy-os.yml
    prepare: ../default-undeploy/prepare.yml
    converge: ../default-undeploy/converge.yml
    verify: ../default-undeploy/verify.yml
verifier:
  name: ansible
