---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: ubuntu1804
    image_name: ansible-dev-ubuntu-18-04
    groups: ['ssh']

  - name: ubuntu2004
    image_name: ansible-dev-ubuntu-20-04
    groups: ['ssh']

  - name: ubuntu2204
    image_name: ansible-dev-ubuntu-22-04
    groups: ['ssh']
provisioner:
  name: ansible
  playbooks:
    create: ../default/create-os.yml
    destroy: ../default/destroy-os.yml
    prepare: ../default-deploy/prepare.yml
    converge: ../default-deploy/converge.yml
    verify: ../default-deploy/verify.yml
verifier:
  name: ansible
