---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  # DEBIAN
  - name: debian11
    image_name: Debian 11 64-bit (Ansible)
    groups: ['ssh']
  - name: debian12
    image_name: Debian 12 64-bit
    groups: ['ssh']
  - name: debian13
    image_name: Debian 13 64-bit
    groups: ['ssh']
provisioner:
  name: ansible
  playbooks:
    create: ../default/create-os.yml
    destroy: ../default/destroy-os.yml
    prepare: ../default-undeploy/prepare.yml
    converge: ../default-undeploy/converge.yml
    verify: ../default-undeploy/verify.yml
verifier:
  name: ansible
