---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: ubuntu1804
    template_name: ubuntu-18-04
    groups: ['ssh']
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    destroy: ../default/destroy.yml
    converge: ../default-install/converge.yml
    verify: ../default-install/verify.yml
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
verifier:
  name: ansible
