---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: ubuntu1804
    image_name: ansible-dev-ubuntu-18-04

  - name: ubuntu2004
    image_name: ansible-dev-ubuntu-20-04

  - name: ubuntu2204
    image_name: ansible-dev-ubuntu-22-04

  - name: centos7
    image_name: ansible-dev-centos-7

  - name: centos8
    image_name: ansible-dev-centos-8-stream

  - name: centos9
    image_name: ansible-dev-centos-9-stream
provisioner:
  name: ansible
  playbooks:
    create: ../default/create-os.yml
    destroy: ../default/destroy-os.yml
    prepare: ../default-undeploy/prepare.yml
    converge: ../default-undeploy/converge.yml
    verify: ../default-undeploy/verify.yml
verifier:
  name: ansible
